### ISSUE TITLE
unused import

### ISSUE THREAD

**Issue by Smug246** [addi00000/pycloak#3]
line 9 unused import

**Comment by addi00000** [comment]
True

**Comment by Smug246** [comment]
i got u

**Comment by addi00000** [comment]
this is already fixed in my local repo and will be gone soon

**Comment by xor5** [comment]
when you tab the vscode suggestions and it imports some random module

**Comment by addi00000** [comment]
Yeah. very sad

**Comment by xor5** [comment]
> fix that gap in line 1 too. might be my ocd but cant allow that

dont think that i have ocd but that still looks terrible, please fix

**Comment by addi00000** [comment]
> fix that gap in line 1 too. might be my ocd but cant allow that

This is critical to the functioning of the program

**Comment by xor5** [comment]
> > fix that gap in line 1 too. might be my ocd but cant allow that
> 
> This is critical to the functioning of the program

it is critical of me being able to read the code
